version: 18
jobs:
- name: 同步
  steps:
  - !PushRepository
    name: 同步
    remoteUrl: https://github.com/20020314/GenshinLauncher
    userName: '20020314'
    passwordSecret: GIT-token
    withLfs: false
    force: true
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  triggers:
  - !BranchUpdateTrigger {}
  retryCondition: never
  maxRetries: 3
  retryDelay: 30
  cpuRequirement: 250
  memoryRequirement: 256
  timeout: 3600
