name: .NET Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    strategy:
      matrix:
        configuration: [Debug, Release]

    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    # 安装 .NET Core
    - name: Install .NET Core
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 5.0.x

    # 添加 MSBuild.exe 到环境变量: https://github.com/microsoft/setup-msbuild
    - name: Setup MSBuild.exe
    - uses: microsoft/setup-msbuild@v1.1
      with:
        msbuild-architecture: x64

    # 安装 NuGet
    - name: Setup NuGet
    - uses: nuget/setup-nuget@v1.0.6
      with:
        nuget-version: 'latest'

    # 还原 NuGet 包
    - name: NuGet restore
      run: nuget restore

    # 编译整个项目
    - name: Build the solution
      run: msbuild /p:Configuration=$env:Configuration
      env:
        Configuration: ${{ matrix.configuration }}
